[template]
src = "../templates/site/fiak-site-config.js.tmpl"
dest = "/etc/extendedmind/site/filosofianakatemia-config.js"
keys = [
    "/filosofianakatemia/backend",
    "/filosofianakatemia/backendcollective"
]
